### ISSUE TITLE
version for kernel 5.18

### ISSUE THREAD

**Issue by tilsgee** [MeowIce/nvidia-legacy#1]
Is there a mismatch? Where a version for kernel 5.18 , written as "5.8" in here. or, still in development? (For kernel 5.18)

**Comment by MeowIce** [comment]
> Is there a mismatch? Where a version for kernel 5.18 , written as "5.8" in here. or, still in development? (For kernel 5.18)


I will release a patch for 5.18 soon. And 5.8 is  5.8.
