### ISSUE TITLE
New patches for kernel 6.1

### ISSUE THREAD

**Issue by pigeonskiller** [MeowIce/nvidia-legacy#12]
Just for info Debian SID already has drivers patched for kernel 6.1 called nvidia-legacy-340xx-driver.

Please check it out here:
https://metadata.ftp-master.debian.org/changelogs//non-free/n/nvidia-graphics-drivers-legacy-340xx/nvidia-graphics-drivers-legacy-340xx_340.108-17_changelog

**Comment by MeowIce** [comment]
It should work with 6.1 :)

**Comment by pigeonskiller** [comment]
It doesn't. Infact there are patches for kernel 6.1 and now also for 6.2. Please take a look here:

https://github.com/archlinux-jerry/nvidia-340xx
