### ISSUE TITLE
LFS download error

### ISSUE THREAD

**Issue by Davilarek** [MeowIce/nvidia-legacy#13]
```
Downloading 5.18/NVIDIA-Linux-x86_64-390.151-5.18.run (127 MB)
Error downloading object: 5.18/NVIDIA-Linux-x86_64-390.151-5.18.run (c6b0e50): Smudge error: Error downloading 5.18/NVIDIA-Linux-x86_64-390.151-5.18.run (c6b0e5011ca60ddc4e64932450971d9dd04aa31cd34bf8fa95b2c450e7742519): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

**Comment by MeowIce** [comment]
> ```
> Downloading 5.18/NVIDIA-Linux-x86_64-390.151-5.18.run (127 MB)
> Error downloading object: 5.18/NVIDIA-Linux-x86_64-390.151-5.18.run (c6b0e50): Smudge error: Error downloading 5.18/NVIDIA-Linux-x86_64-390.151-5.18.run (c6b0e5011ca60ddc4e64932450971d9dd04aa31cd34bf8fa95b2c450e7742519): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
> ```

Download via the website instead ?

**Comment by Davilarek** [comment]
gives me 1kb zip file with file with contents:
```
version https://git-lfs.github.com/spec/v1
oid sha256:c6b0e5011ca60ddc4e64932450971d9dd04aa31cd34bf8fa95b2c450e7742519
size 126767217
```
