### ISSUE TITLE
It should work with 6.1 :)

### ISSUE THREAD

**Issue by pigeonskiller** [MeowIce/nvidia-legacy#14]
It should work with 6.1 :)

_Originally posted by @MeowIce in https://github.com/MeowIce/nvidia-legacy/issues/12#issuecomment-1407278736_

It doesn't. Infact there are patches for kernel 6.1 and now also for 6.2. Please take a look here:

https://github.com/archlinux-jerry/nvidia-340xx

**Comment by MeowIce** [comment]
Updated ^^
