### ISSUE TITLE
Will 6.5 work on kali linux 6.4 ?

### ISSUE THREAD

**Issue by mhajji29** [MeowIce/nvidia-legacy#18]
A week ago, i tried to install nvidia driver 340xx (6.3) on kali linux (6.4) but lightdm failed to start, so i was forced to reinstall kali, now i am afraid that if i installed 6.5 driver will make my system stop working!

Last kernel version in kali linux is 6.4!

What should i do?

**Comment by MeowIce** [comment]
> A week ago, i tried to install nvidia driver 340xx (6.3) on kali linux (6.4) but lightdm failed to start, so i was forced to reinstall kali, now i am afraid that if i installed 6.5 driver will make my system stop working!
> 
> Last kernel version in kali linux is 6.4!
> 
> What should i do?

Try it and see...

**Comment by disc0nct** [comment]
Tried and i got this

**Comment by disc0nct** [comment]
![IMG_20230915_063806](https://github.com/MeowIce/nvidia-legacy/assets/17936240/1f6e1b08-121d-4a5a-9e5f-5141552e9ac7)

**Comment by MeowIce** [comment]
> ![IMG_20230915_063806](https://github.com/MeowIce/nvidia-legacy/assets/17936240/1f6e1b08-121d-4a5a-9e5f-5141552e9ac7)
> 

Try using another/mainline kernels, the driver is blaming bout the kernel signing stuff.

**Comment by dolphin-cat** [comment]
i have kali 6.5 and tried to install 340.108 patched for 6.5, i have the same error. how do i fix this?

**Comment by mhajji29** [comment]
I've tried a lot of methods but nothing has worked, but i found this method, and it is working in my Kali Linux, i installed 340xx nvidia driver without any problem

https://gist.github.com/oprizal/998635a2ff5cbecb0519455c12b2994f

Thank you MeowIce anyway

**Comment by mhajji29** [comment]
I've tried a lot of methods but nothing has worked, but i found this method, and it is working in my Kali Linux, i installed 340xx nvidia driver without any problem

https://gist.github.com/oprizal/998635a2ff5cbecb0519455c12b2994f
