### ISSUE TITLE
Nvidia 340.108 patch for kernel 6.6

### ISSUE THREAD

**Issue by pigeonskiller** [MeowIce/nvidia-legacy#19]
Hi developers,

just to inform you that a patch for kernel 6.6 is available to compile driver 340.108.

You may find it here:
https://aur.archlinux.org/packages/nvidia-340xx-dkms

Thank you for supporting old hardware.

**Comment by pigeonskiller** [comment]
Hi,

sorry I have already installed the latest driver from Debian SID since then and it is working fine.

Anyway just before I prepared a *.run version with all patches (6.6 included) but I've never tested it: if you are interested mail me and I will send it to you.

Bye

Da: MeowIce
Inviato: domenica 26 novembre 2023 17:10
A: MeowIce/nvidia-legacy
Cc: pigeonskiller; Author
Oggetto: Re: [MeowIce/nvidia-legacy] Nvidia 340.108 patch for kernel 6.6(Issue #19)

Could you try this very experimentally build ? Excuse for Discord link, I can't post .run file here :p
https://cdn.discordapp.com/attachments/677513197116194831/1178367028550176808/NVIDIA-Linux-x86_64-340.108-patched-6.6-vDEV.run

**Comment by MeowIce** [comment]
Tested myself and the patch worked.
Added for 6.6.
