### ISSUE TITLE
Kernel update (5.18.6 -> 5.18.7)

### ISSUE THREAD

**Issue by uncl1ckable** [MeowIce/nvidia-legacy#2]
after updating the kernel, it stopped loading, can recommendations be made?
Driver version: 390.151

**Comment by MeowIce** [comment]
> after updating the kernel, it stopped loading

You reinstall the driver by re-run the install script.

> can recommendations be made?

If you could, try install it with DKMS.

**Comment by uncl1ckable** [comment]
I also ran into such a problem that I turned on nouveau and run plasma (x11/wayland) and the screen freezes completely after loading, no clicks work, could you give any recommendations on this too?

**Comment by uncl1ckable** [comment]
I would like to open a terminal, but I don't know how to do it.

**Comment by MeowIce** [comment]
> I also ran into such a problem that I turned on nouveau and run plasma (x11/wayland) and the screen freezes completely after loading, no clicks work, could you give any recommendations on this too?

I also had the same problem after a fresh installation of any Linux distro. But it does not happen immediately, only if I had some windows opened. There's no way to fix this. The only option is to install the nvidia driver.

**Comment by MeowIce** [comment]
> I would like to open a terminal, but I don't know how to do it.

You might want to switch to TTY by pressing `Ctrl` + `Alt` + `F1/2/3...` any from 1 to 6.

**Comment by uncl1ckable** [comment]
Wow, it works, thank you very much for your help and for a very quick response. I hope this will help others as well.
