### ISSUE TITLE
Error when try to download 390.151 (5.18+)

### ISSUE THREAD

**Issue by marciosalomao** [MeowIce/nvidia-legacy#20]
When I try to download the 390.151 (5.18+) patched version, the file (121MB) cant download and just appear the message below on browser:

version https://git-lfs.github.com/spec/v1
oid sha256:c6b0e5011ca60ddc4e64932450971d9dd04aa31cd34bf8fa95b2c450e7742519
size 126767217

Or the content of the file NVIDIA-Linux-x86_64-390.151-5.18.run downloaded is the same above.

**Comment by MeowIce** [comment]
Git LFS issues. I can't fix that. Therefore, I'll move driver builds to [SourceForge](https://sourceforge.net/projects/nvidia-legacy/files/) in the future.

**Comment by RafaelTrepaUnCarballo** [comment]
> Git LFS issues. I can't fix that. Therefore, I'll move driver builds to [SourceForge](https://sourceforge.net/projects/nvidia-legacy/files/) in the future.

The file isn't available in Sourceforge, the  390.151 folder is empty
https://sourceforge.net/projects/nvidia-legacy/files/390.151/
