### ISSUE TITLE
Nvidia 340.108 patch for kernel 6.8

### ISSUE THREAD

**Issue by pigeonskiller** [MeowIce/nvidia-legacy#23]
Hi developers,

just to inform you that a patch for kernel 6.8 is available to compile driver 340.108.

You may find it here:
https://aur.archlinux.org/packages/nvidia-340xx-dkms

or here:
https://nvidia.if-not-true-then-false.com/patcher/NVIDIA-340xx/

Thank you for supporting old hardware.

**Comment by MeowIce** [comment]
Updated, please check the Release.
