### ISSUE TITLE
[k5.18 : d340.108] Kernel panic?

### ISSUE THREAD

**Issue by rustzz** [MeowIce/nvidia-legacy#4]
dmesg: https://pastebin.com/pTwN5r2Q
[nvidia-installer.log](https://github.com/MeowIce/nvidia-legacy/files/9441865/nv-log.log)
uname -a: Linux wired-pc 5.15.63 #1 SMP PREEMPT Mon Aug 29 09:45:38 +05 2022 x86_64 GNU/Linux

**Comment by MeowIce** [comment]
> dmesg: https://pastebin.com/pTwN5r2Q [nvidia-installer.log](https://github.com/MeowIce/nvidia-legacy/files/9441865/nv-log.log) uname -a: Linux wired-pc 5.15.63 #1 SMP PREEMPT Mon Aug 29 09:45:38 +05 2022 x86_64 GNU/Linux

Which distro ? If Mint, try install supported kernel. This is a known problem on Mainline kernels.

**Comment by rustzz** [comment]
Installing
Distro: Artix Linux (openrc) custom kernel 5.15.53 from kernel.org

**Comment by MeowIce** [comment]
> Installing Distro: Artix Linux (openrc) custom kernel 5.15.53 from kernel.org

I also got this problem while installing on some kernels. It's not a big issue I guess. If you got kernel panic, try to press `<-` and `->` to update the screen and you'll see the current operation.

**Comment by rustzz** [comment]
when i press the arrow buttons it doesn't go away. but after installing the driver works.

also i have a bug with working on flutter. I think that it is with the original driver. but maybe you can fix this error. or what is it?
`[FATAL:flutter/shell/gpu/gpu_surface_gl_delegate.cc(50)] Check failed: gl_version_string. The GL proc resolver's glGetString(GL_VERSION) failed`

**Comment by MeowIce** [comment]
> when i press the arrow buttons it doesn't go away. but after installing the driver works.
> 
> also i have a bug with working on flutter. I think that it is with the original driver. but maybe you can fix this error. or what is it?
> `[FATAL:flutter/shell/gpu/gpu_surface_gl_delegate.cc(50)] Check failed: gl_version_string. The GL proc resolver's glGetString(GL_VERSION) failed`

If the installation works, no worry. I think the error above is because the OpenGL library is too old...or invalid.

**Comment by rustzz** [comment]
ok
