### ISSUE TITLE
Giving credit to the owner of the patch

### ISSUE THREAD

**Issue by Rainb0-0** [MeowIce/nvidia-legacy#5]
### The source of the patch

**[If not true then false](https://www.if-not-true-then-false.com/2020/inttf-nvidia-patcher/)**

**Comment by MeowIce** [comment]
> ### The source of the patch
> 
> **[If not true then false](https://www.if-not-true-then-false.com/2020/inttf-nvidia-patcher/)**
> 
> 

Thanks for reminding me. Will be added soon 👌✨.
