### ISSUE TITLE
Button download

### ISSUE THREAD

**Issue by uncl1ckable** [MeowIce/nvidia-legacy#9]
I can't find the file download button, HELP ME)) (driver version 390.151)

**Comment by MeowIce** [comment]
> I can't find the file download button, HELP ME)) (driver version 390.151)

Read the docs.

**Comment by uncl1ckable** [comment]
There is no button, it's an LFS file, how do I download it?

**Comment by uncl1ckable** [comment]
I read the documentation and found nothing.

**Comment by uncl1ckable** [comment]
![image](https://user-images.githubusercontent.com/75583263/203141457-b3124d65-33e6-481a-a279-e20f7e60e1ee.png)
Here is what I get.

**Comment by uncl1ckable** [comment]
?

**Comment by uncl1ckable** [comment]
And is it also possible to migrate to the 6.0+ kernel version?
